// src/store/initialState.ts
import { type GroupStats, type AttachedItem } from "./types";

export const defaultGroupStats = (): GroupStats => ({
  total_files: 0,
  total_dirs: 0,
  total_size: 0,
  token_count: 0,
});

export const initialState = {
  rootPath: null,
  selectedPath: null,
  allGroups: new Map(),
  groups: [],
  projectStats: null,
  fileTree: null,
  fileMetadataCache: null,
  activeScene: "dashboard" as "dashboard" | "settings",
  editingGroupId: null,
  inlineEditingGroup: null,
  isScanning: false,
  isRescanning: false,
  scanProgress: { currentFile: null, currentPhase: "scanning" as const },
  isUpdatingGroupId: null,
  tempSelectedPaths: null,
  isGroupEditorPanelVisible: false,
  isEditorPanelVisible: false,
  activeEditorFile: null,
  activeEditorFileContent: null,
  isEditorLoading: false,
  activeEditorFileExclusions: null,
  syncEnabled: false,
  syncPath: null,
  customIgnorePatterns: [],
  isWatchingFiles: false,
  exportUseFullTree: false,
  exportOnlyTree: false,
  exportWithLineNumbers: true,
  exportWithoutComments: false,
  exportRemoveDebugLogs: false,
  exportSuperCompressed: false,
  exportClaudeMode: false,
  exportDummyLogic: false,
  alwaysApplyText: null,
  appendIdePrompt: false,
  appendGroupPrompt: false,
  exportExcludeExtensions: [],
  gitExportModeIsContext: false,
  profiles: ["default"],
  activeProfile: "default",
  isSidebarVisible: true,
  recentPaths: [],
  nonAnalyzableExtensions: [],
  nonAnalyzableFolders: [],
  isGitPanelVisible: false,
  gitRepoInfo: null,
  gitStatus: null,
  gitCommits: [],
  gitLogState: "idle" as "idle" | "loading_repo" | "loading_commits" | "error",
  gitCurrentPage: 0,
  hasMoreCommits: true,
  originalGitBranch: null,
  gitBranches: [],
  isKiloPanelVisible: false,
  isKiloServerRunning: false,
  kiloLogs: [],
  isKiloInstalled: null,
  selectedKiloModel: "kilo/minimax/minimax-m2.5:free",
  kiloAvailableModels: [],
  kiloTaskStatus: "idle" as const,
  isPatchPanelVisible: false,
  isPatchServerRunning: false,
  patchLogs: [],
  patchTasks: [] as import("./types").PatchTaskUI[],
  patchTaskStatus: "idle" as const,
  isAiPanelVisible: false,
  aiChatMode: "ask" as "ask" | "context" | "mc",
  openRouterApiKey: "",
  googleApiKey: "",
  nvidiaApiKey: "",
  allAvailableModels: [],
  aiModels: [],
  chatMessages: [],
  isAiPanelLoading: false,
  chatSessions: [],
  activeChatSessionId: null,
  abortController: null,
  activeChatSession: null,
  temperature: 1.0,
  topP: 1.0,
  topK: 0, // 0 means not set
  maxTokens: 0, // 0 means not set
  geminiThinkingLevel: "MEDIUM" as const,
  systemPrompt: "",
  streamResponse: true,
  selectedAiModel: "openai/gpt-3.5-turbo",
  subAgentModel: "",
  editingMessageIndex: null,
  aiAttachedFiles: [] as AttachedItem[],
  kiloPort: 9999,
  patchPort: 9998,
  discordWebhookUrl: "",
};

export type InitialState = typeof initialState;
